name: release
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, 'skip ci') == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./

